// Actual installed Ferrari and Corolla; no fabricated assets or external analysis requests.
// References: https://playwright.dev/docs/api/class-page and https://playwright.dev/docs/api/class-mouse#mouse-wheel
import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {mkdir,readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.STUDIO_URL||'http://127.0.0.1:8788',artifacts=path.join(os.tmpdir(),'car-parts-browser-results');await mkdir(artifacts,{recursive:true});
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'}),checks=[],errors=[],failures=[];let posts=0;
page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.method()==='POST'&&new URL(request.url()).pathname==='/api/repair/chat')posts++;});
try{
 const catalog=await(await page.request.get(base+'/api/repair/catalog')).json();assert.equal(catalog.vehicles.length,6);assert.equal(catalog.vehicles.filter(v=>v.prepared).length,2);
 const ferrari=catalog.vehicles.find(v=>v.id==='ferrari-458-demo'),corolla=catalog.vehicles.find(v=>v.id==='corolla-prepared-demo');assert.notEqual(ferrari.prepared.asset,corolla.prepared.asset);
 await page.goto(base+'/fix.html');await page.waitForFunction(()=>document.getElementById('showroom-name').textContent.startsWith('Ferrari 458'),null,{timeout:45000});
 await page.evaluate(async()=>{const url=performance.getEntriesByType('resource').find(entry=>new URL(entry.name).pathname==='/src/fix-viewer.js').name;const {Showroom,RepairViewer}=await import(url);window.__steps=[];const move=Showroom.prototype.move;Showroom.prototype.move=function(delta){window.__world=this;window.__steps.push(delta);return move.call(this,delta);};const explode=RepairViewer.prototype.setExplode;RepairViewer.prototype.setExplode=function(amount){window.__repair=this;return explode.call(this,amount);};});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1&&document.documentElement.scrollWidth<=innerWidth+1));
 await page.locator('#vehicle-list').hover();await page.mouse.wheel(0,550);await page.waitForFunction(()=>document.getElementById('showroom-name').textContent==='Toyota Corolla · 2020');
 assert.deepEqual(await page.evaluate(()=>__steps),[1]);assert.equal(await page.evaluate(()=>scrollY),0);
 const models=await page.evaluate(()=>__world.entries.map(entry=>{let triangles=0,materials=0;entry.model.traverse(node=>{if(node.isMesh){triangles+=(node.geometry.index?.count||node.geometry.attributes.position.count)/3;materials+=Array.isArray(node.material)?node.material.length:1;}});return{id:entry.vehicle.id,triangles,materials,finite:entry.model.matrixWorld.elements.every(Number.isFinite)};}));
 assert.deepEqual(models.map(v=>v.id),['ferrari-458-demo','corolla-prepared-demo']);assert.deepEqual(models.map(v=>v.triangles),[358788,205990]);assert.ok(models.every(v=>v.materials>0&&v.finite));
 checks.push('Six catalog records, two distinct real rendered cars, and one native wheel gesture changes Ferrari to Corolla without vertical scrolling');console.log('PASS '+checks.at(-1));
 await page.locator('#showroom-previous').click();await page.waitForFunction(()=>__world.position===0);
 await page.screenshot({path:path.join(artifacts,'ferrari-showroom.png'),timeout:45000});console.log('SCREENSHOT '+path.join(artifacts,'ferrari-showroom.png'));
 await page.locator('#vehicle-list').focus();await page.keyboard.press('Enter');await page.locator('#viewer-controls').waitFor({state:'visible',timeout:45000});await page.waitForFunction(()=>__repair.amount===.5);
 const wheels=await page.evaluate(()=>({parts:__repair.parts.map(part=>({id:part.id,family:part.family,offset:part.offsetMeters,position:__repair.groups.get(part.id).position.toArray()})),finite:[...__repair.groups.values()].every(group=>group.position.toArray().every(Number.isFinite))}));assert.equal(wheels.parts.length,5);assert.equal(wheels.finite,true);assert.ok(wheels.parts.every(part=>part.family===null));
 for(const part of wheels.parts)assert.deepEqual(part.position,part.offset.map(value=>value*.5));
 assert.equal(await page.locator('#explode').inputValue(),'50');assert.equal(await page.locator('#parts-list .part-row').count(),0);assert.ok((await page.locator('#chat-log').innerText()).includes(ferrari.repairNotice));
 const bytes=await readFile(new URL('../design_mod/public/assets/ferrari_ao.png',import.meta.url));const photo={name:'local-attachment.png',mimeType:'image/png',buffer:bytes};
 await page.locator('#damage-photos').setInputFiles(photo);await page.waitForFunction(()=>document.querySelectorAll('#photos .photo').length===1&&!document.getElementById('message-input').disabled);assert.equal(await page.locator('#send-message').isDisabled(),true);assert.equal(await page.locator('#confirm-repair').isDisabled(),true);
 checks.push('Ferrari has four finite wheel offsets plus context at 50%, no exterior repair families, visible repair notice, and disabled Send even with a photo');console.log('PASS '+checks.at(-1));
 await page.locator('#change-car').click();await page.locator('#showroom-next').click();await page.waitForFunction(()=>document.getElementById('showroom-name').textContent==='Toyota Corolla · 2020');await page.locator('#vehicle-list').focus();await page.keyboard.press('Enter');await page.locator('#viewer-controls').waitFor({state:'visible',timeout:45000});
 await page.locator('#damage-photos').setInputFiles(photo);await page.waitForFunction(()=>document.querySelectorAll('#photos .photo').length===1&&!document.getElementById('message-input').disabled);assert.equal(await page.locator('#send-message').isEnabled(),true);assert.equal(await page.evaluate(()=>__repair.groups.size),43);assert.equal(posts,0);assert.deepEqual(errors,[]);
 checks.push('Corolla retains 43 assemblies and enables Send after local attachment; zero external damage requests and no browser exceptions');console.log('PASS '+checks.at(-1));
}catch(error){failures.push(error.message);console.error('FAIL '+error.message);console.error(JSON.stringify(await page.evaluate(()=>({title:document.getElementById('showroom-name')?.textContent,error:document.getElementById('error')?.textContent,chatError:document.getElementById('chat-error')?.textContent})).catch(()=>({}))));process.exitCode=1;}
finally{await writeFile(path.join(artifacts,'vehicle-library-results.json'),JSON.stringify({checks,errors,failures,damageRequests:posts},null,2));await browser.close();}
