import * as THREE from 'three';
import {createPartGroup,disposeGroup} from './geometry.mjs';
import {regions,styles} from './catalog.mjs';
import {hardwareIllustration,connectionDrawing,benchIllustration,cautionDrawing} from './manual-illustrations.mjs';
import {manualStyle} from './manual-style.mjs';

export const mountingReferences=[
  {title:'Liberty Walk · Ferrari 458 body-kit families',url:'https://libertywalk.co.jp/bodykit/ferrari-458/',note:'Real examples of lip kits, full bumpers, side diffusers, GT wings and ducktails. Reference only; no manufacturer CAD is bundled.'},
  {title:'MEC Design · Ferrari 458 component program',url:'https://www.mecdesign.de/new/pricelists/en/Ferrari_458_Pricelist_International_Complete.pdf',note:'Some listed 458 Italia/Spider additions use adhesive attachment. These are product-specific methods, not approval for our geometry.'},
  {title:'Maxton Design · Installation manuals',url:'https://maxtondesign.com/pages/manuals',note:'Separate instructions for bolted splitters, bonded spoiler caps and other assemblies. A single generic clip is not a universal mounting interface.'},
  {title:'Maxton Design · Corolla sedan spoiler cap',url:'https://maxtondesign.com/products/spoiler-cap-toyota-corolla-mk12-sedan',note:'A sedan-specific ABS cap supplied with 3M tape. The hatchback and sedan are not interchangeable fitments.'},
  {title:'Formlabs · End-use application guidance',url:'https://formlabs.com/support/End-use-applications/',note:'Material, print process and environmental/stress testing matter before field deployment; a valid STL does not establish part suitability.'},
];
const h=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function partIllustration(part,vehicleId){
  const group=createPartGroup(part.region,part.style,undefined,vehicleId),mesh=group.children.find(m=>part.name.startsWith(m.name+'-'));
  const edges=new THREE.EdgesGeometry(mesh.geometry,28),positions=edges.attributes.position;
  const project=v=>[v.x*.88+v.z*.48,v.z*.3-v.y];
  const points=[];for(let i=0;i<positions.count;i++)points.push(project(new THREE.Vector3().fromBufferAttribute(positions,i)));
  const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);
  const scale=Math.min(410/(maxX-minX),155/(maxY-minY)),cx=(minX+maxX)/2,cy=(minY+maxY)/2;
  const xy=p=>[230+(p[0]-cx)*scale,110+(p[1]-cy)*scale];let d='';
  for(let i=0;i<points.length;i+=2){const a=xy(points[i]),b=xy(points[i+1]);d+=`M${a[0].toFixed(1)} ${a[1].toFixed(1)}L${b[0].toFixed(1)} ${b[1].toFixed(1)}`;}
  const markers=mesh.userData.mountPoints.map((m,i)=>{const p=xy(project(new THREE.Vector3(...m.position))),labelY=i%2?194:24;return `<path d="M${p[0]} ${p[1]}L${p[0]} ${labelY}" fill="none" stroke="#111" stroke-width=".7"/><circle cx="${p[0]}" cy="${labelY}" r="10" fill="#fff" stroke="#111"/><text x="${p[0]}" y="${labelY+3.5}" text-anchor="middle" font-family="Arial,sans-serif" font-size="10" fill="#111">${i+1}</text>`;}).join('');
  edges.dispose();disposeGroup(group);mesh.material.dispose();
  return `<svg viewBox="0 0 460 220" role="img" aria-label="${h(part.name)} with numbered concept holes"><path d="${d}" fill="none" stroke="#111" stroke-width="1.1" stroke-linejoin="round"/>${markers}</svg>`;
}

export function connectionIllustration(){return connectionDrawing();}

export function assemblyGuide(manifest){
  const count=manifest.parts.length,holes=manifest.parts.reduce((n,p)=>n+p.mounting.holes.length,0);
  const partRows=manifest.parts.map((p,i)=>`<article class="part"><div class="part-id"><b>P${String(i+1).padStart(2,'0')}</b><span>1×</span></div>${partIllustration(p,manifest.vehicleId)}<h3>${h(regions.find(r=>r.id===p.region).name)}${p.name.includes('left')?' · Left':p.name.includes('right')?' · Right':''} / ${h(styles.find(s=>s.id===p.style).name)}</h3><p>${p.dimensionsMm.join(' × ')} mm · ${p.mounting.holes.length} concept holes</p><code>${h(p.name)}</code></article>`).join('');
  const hardwareNames={H1:'Metal bolt',H2:'Metal washer',H3:'Locking nut',H4:'Backing plate',H5:'Isolation pad'};
  const hardwareCards=manifest.hardware.map(item=>`<article class="hardware-item"><div class="part-id"><b>${h(item.id)}</b><span>${item.quantity}×</span></div>${hardwareIllustration(item.id)}<p>${hardwareNames[item.id]}</p></article>`).join('');
  const footer=(n)=>`<footer><span>FORMA / ${h(manifest.vehicleName)} / REV 04</span><span>BENCH DEMO ONLY · ${n}</span></footer>`;
  const page=(n,title,body)=>`<section class="page"><div class="page-head"><span>ASSEMBLY FIELD GUIDE</span><span>${n}</span></div><h2>${title}</h2>${body}${footer(n)}</section>`;
  const step=(n,title,body,kind)=>`<article class="step"><div class="step-heading"><b>${n}</b><h3>${title}</h3></div>${benchIllustration(kind)}<p>${body}</p></article>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FORMA — ${h(manifest.vehicleName)} assembly guide</title><style>
  ${manualStyle}</style></head><body><p class="print-note">Self-contained guide · Print / Save as PDF using your browser · Diagrams are not to scale and are not drilling templates.</p>
  <section class="page"><div class="page-head"><span>FORMA / ASSEMBLY INSTRUCTIONS / CONCEPT EDITION</span><span>00</span></div><h1>Your kit.<br>In pieces.</h1><p class="cover-subtitle">${h(manifest.vehicleName)} · Body-kit concepts</p><div class="cover-drawing">${cautionDrawing()}</div><div class="facts"><div><b>${String(count).padStart(2,'0')}</b><span>PRINTED CONCEPT PARTS</span></div><div><b>${String(holes).padStart(2,'0')}</b><span>ILLUSTRATIVE CONNECTIONS</span></div><div><b>mm</b><span>Z-UP STL FILES</span></div></div><div class="warning"><strong>VISUALIZATION + BENCH DEMONSTRATION ONLY</strong><p>This is a guide to a loose connection concept, not a vehicle installation manual. Hole positions, hardware, materials and loads have not been validated. Do not drill, remove vehicle parts, or install this kit on a car.</p></div><p class="small">Start with the parts. Match the hardware IDs. Follow the drawings.<br>Original line illustrations · No manufacturer affiliation · Not to scale.</p>${footer('00')}</section>
  ${page('01','Meet your kit.',`<p>Match every filename with its part card. A full side-skirt selection includes separate left and right parts. Existing car geometry and purchased metal fasteners are not included in these STL files.</p><div class="parts">${partRows}</div><div class="box"><h3>Before you print</h3><p>Import in millimetres, keep the part at 100% scale and verify the displayed dimensions. These full-size files can exceed industrial printer build volumes. No segmented joints or desktop-printer split strategy have been engineered. Request a process plan rather than automatically cutting and gluing the model.</p></div>`)}
  ${page('02','Lay everything out.',`<p>Counts for your selected kit. Hardware is purchased or fabricated, not supplied as printable STL geometry.</p><div class="hardware-grid">${hardwareCards}</div><table class="bom"><thead><tr><th>ID</th><th>EXAMPLE HARDWARE / NOT A PROCUREMENT SPECIFICATION</th><th>QTY</th></tr></thead><tbody>${manifest.hardware.map(item=>`<tr><td>${item.id}</td><td>${h(item.name)}</td><td>${item.quantity}</td></tr>`).join('')}</tbody></table><div class="two-col"><div class="box"><h3>Prepare the bench</h3><p>Calipers, a protective mat, eye protection and hand tools suited to the sample hardware. Keep parts loose. Never force alignment with a power tool.</p></div><div class="box"><h3>Specification pending</h3><p>Grade, length, torque, locking, plate thickness, pad material and tolerances are unverified. Do not print metal fasteners for vehicle attachment.</p></div></div><div class="warning"><strong>ILLUSTRATIVE HARDWARE ONLY</strong><p>M6 and the backing-plate dimensions are examples. They do not define a safe attachment to a real car. Clips alone have not been validated for aerodynamic retention.</p></div>`)}
  ${page('03','One connection. Seven layers.',`<p>Match the IDs to page 02. The dotted line is the common hole axis. The printed-part section is simplified for clarity; the vehicle substrate is not represented.</p><div class="hero-illustration">${connectionIllustration()}</div><div class="two-col"><div class="box"><h3>Above the printed part</h3><p>Metal bolt H1 + washer H2. Threads are an illustration, not a manufacturing file.</p></div><div class="box"><h3>Below the printed part</h3><p>Pad H5 + plate H4 + washer H2 + nut H3. A real vehicle needs an additional verified attachment interface.</p></div></div><p class="small">Arrange a loose bench sample only. Hand-start without applying installation torque. Example clearance: Ø6.6 mm; final tolerance needs process validation.</p>`)}
  ${page('04','The bench sequence.',`<div class="steps">${step('1','Match the part.','Match the part ID on page 01. Check the filename and 100% scale; this does not verify vehicle fitment.','identity')}${step('2','Check the sample.','Measure dimensions. Inspect holes, edges and layers. Reject cracks, warping or blocked holes.','inspect')}${step('3','Count one connection.','One bolt, two washers, one nut, one plate and one pad. Repeat for each illustrated hole.','arrange')}${step('4','Arrange. Hand-start.','Follow page 03 on a loose sample. Do not force parts or apply installation torque.','assemble')}${step('5','Record what is missing.','Use page 05 to record measurements, material testing and engineering review still needed.','record')}${step('6','Stop at the bench.','Do not attach to a car. Vehicle installation requires a separately approved design and manual.','hold')}</div><div class="hold">VEHICLE INSTALLATION: ON HOLD</div>`)}
  ${page('05','From concept to fitment.',`<p>These are release gates, not completed checks. Each needs measured evidence and responsible engineering approval before a self-installation manual can be issued.</p><ul class="checklist"><li>Exact vehicle year / trim / body variant and relevant OEM instructions confirmed.</li><li>Mounting surfaces scanned or measured; datum frame, hole centers and access documented.</li><li>Attachment substrate, local reinforcement and load path defined; clearance from wiring, sensors, heat sources and moving parts checked.</li><li>Hardware grade, thread engagement, bolt length, locking system, tightening values and sequence approved.</li><li>Printed material, build orientation, thickness, tolerances, finishing and batch QA validated for the intended environment.</li><li>Pull-out, vibration, fatigue, temperature, UV, moisture and intended aerodynamic-load validation completed.</li><li>Sealing, drainage, corrosion isolation, edges and service/removal method resolved.</li><li>Vehicle-level clearances, retention inspection and applicable road-use requirements reviewed.</li></ul><div class="box"><h3>Fitment record</h3><p>Vehicle / variant: ______________________________<br>Measurement revision: __________________________<br>Material / process / batch: ______________________<br>Engineering reviewer: __________________________<br>Approved installation document: _________________</p></div><p class="small">The current export marks fitVerified = false, roadUseApproved = false and vehiclePatternVerified = false. No torque value, safety factor or road approval has been invented.</p>`)}
  ${page('06','Learn from real systems.',`<p>Primary-source references used to separate styling, mounting and manufacturing. These products and their instructions are not substitutes for our missing vehicle-specific measurements, and are not included designs.</p>${mountingReferences.map(r=>`<div class="ref"><a href="${h(r.url)}" target="_blank" rel="noopener">${h(r.title)} ↗</a><p>${h(r.note)}</p></div>`).join('')}<div class="box"><h3>What is original here?</h3><p>FORMA's part profiles, hole patterns, hardware illustrations and guide diagrams are original prototype work. No branded body-kit CAD or OEM attachment geometry was copied. STL exports contain mesh solids, not editable parametric or OEM CAD.</p></div><p class="small">For this hackathon the detailed mounting scenario is Ferrari 458 visualization only, as selected by the user. Retain this guide, the hardware BOM and manifest with the exported parts.</p>`)}
  </body></html>`;
}
