import {vehicles} from '../catalog.mjs';
export const courses=[
 {slug:'porsche',reference:'2010 911 Carrera 4S · 997.2',engineSpec:'a 3.8 L naturally aspirated flat-six with direct fuel injection',referenceSource:'https://newsroom.porsche.com/en/history/porsche-911-seven-generations-part-6-type-997-16489.html',engineDesign:'The rear-mounted flat-six places three cylinders on each side of the crankshaft. Its low, wide form influences exhaust routing, cooling connections, service access, and the position of mass behind the rear axle.',engineHistory:'The 997 generation developed the 911 architecture through changes including direct fuel injection. The updated 3.8 L S engine was rated at 385 PS by Porsche. The 2010 Carrera 4S is the reference chosen for this course.',vehicleId:'porsche-911-carrera-4s',color:'#aab1bd',title:'An icon.<br><em>Inside out.</em>',tagline:'The sports car as an engineering system.',engine:'Flat-six engine',cylinders:6,architecture:'rear-mounted flat-six',focus:'Follow the coupe’s roofline, rear deck, and wide wheel assemblies. Consider how rear-mounted powertrain packaging influences the space available for cooling, luggage, and the cabin.'},
 {slug:'ferrari',reference:'2012 458 Spider',engineSpec:'a 4,497 cc naturally aspirated 90° V8 with direct fuel injection',referenceSource:'https://www.ferrari.com/en-UG/history/garage/2011/458-spider',engineDesign:'The 458 Spider places its V8 behind the cabin and ahead of the rear axle. Two cylinder banks create a compact length for eight cylinders, while the intake, exhaust, lubrication, and cooling systems must fit around the cockpit and rear structure.',engineHistory:'Ferrari introduced the 458 Spider in 2011. Its naturally aspirated V8 belongs to the 458 family; the Spider adds an open-top packaging challenge. This course selects the 2012 Spider as its engine reference.',vehicleId:'ferrari-458-demo',color:'#b80c18',title:'Performance.<br><em>From within.</em>',tagline:'The art of high-revving performance.',engine:'V8 engine',cylinders:8,architecture:'mid-rear V8',focus:'Explore the open cockpit, sculpted air passages, and wide rear wheels. The 458 family’s mid-rear engine position concentrates powertrain mass behind the occupants and ahead of the rear axle.'},
 {slug:'toyota',reference:'2020 Corolla LE · US market',engineSpec:'a 1.8 L 2ZR-FAE inline-four with Valvematic',referenceSource:'https://pressroom.toyota.com/driving-and-design-highlight-the-all-new-2020-toyota-corolla/',engineDesign:'The transverse inline-four places all four cylinders in one row across the front compartment. This leaves room for a front-drive transaxle alongside the engine. The Valvematic system changes intake valve lift to manage cylinder filling.',engineHistory:'Toyota specified the 1.8 L 2ZR-FAE for the 2020 US Corolla L, LE, and XLE, while the SE and XSE used a different 2.0 L engine. This course selects the LE to keep the engine reference unambiguous.',vehicleId:'toyota-corolla-2020',color:'#c3c8ce',title:'Everyday.<br><em>Extraordinary.</em>',tagline:'The engineering of the everyday.',engine:'Inline-four engine',cylinders:4,architecture:'transverse inline-four',focus:'Inspect the four-door shell, glazing, seating space, and compact wheel assemblies. Everyday vehicle design balances packaging, visibility, efficiency, durability, and manufacturing cost.'}
].map(c=>({...c,vehicle:vehicles.find(v=>v.id===c.vehicleId),engineAsset:null}));
export const getCourse=slug=>courses.find(c=>c.slug===slug)||courses[0];
export function progressKey(course,id,index){return `${course.slug}:${id}:${index}`;}
export function parseLearningRoute(hash){const p=hash.replace(/^#/,'').split('/');if(p[0]==='car')return {page:'car',course:getCourse(p[1])};if(p[0]==='lesson'){const scoped=courses.some(c=>c.slug===p[1]);return {page:'lesson',course:getCourse(scoped?p[1]:null),id:p[scoped?2:1],section:p[scoped?3:2]};}return {page:p[0],course:courses[0]};}
export function migrateProgress(saved){const result={...saved};for(const [k,v]of Object.entries(saved))if(k.split(':').length===2)result[`porsche:${k}`]=v;return result;}
